In [1]:
using Gmsh: gmsh
using Gridap
using GridapGmsh

We import the model:

In [4]:
gmsh.initialize()
gmsh.merge("../data/VenturaAccelerometer/door_2d_V2.msh")

Info    : Reading '../data/VenturaAccelerometer/door_2d_V2.msh'...
Info    : 26 entities
Info    : 116 nodes
Info    : 155 elements
Info    : Done reading '../data/VenturaAccelerometer/door_2d_V2.msh'


We get the required nodes from the mesh.

In [41]:
BC_nodes  = []


#We get all the tags for each node
# tags = gmsh.view.getTags()

fixedtags=[13]

#We get nodes assigned to a specific edge. first value shows the dimension (0: point, 1:edge, 2:surface), the second value represents the subgroup.
for i in fixedtags
    nds = gmsh.model.mesh.getNodesForPhysicalGroup(1, i)[1]

    #It converts the values to integer
    for j in nds
        a = float(j)
        push!(BC_nodes, a)
    end

end

BC_values = zeros(length(BC_nodes))

display(BC_nodes)
display(BC_values)

6-element Vector{Any}:
  1.0
  4.0
 33.0
 34.0
 35.0
 36.0

6-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [59]:
BC_nodes  = []

tags = [14,15]

for i in tags
    nds = gmsh.model.mesh.getNodesForPhysicalGroup(2, i)[1]

    for j in nds
        a = Int8(j)
        push!(BC_nodes, a)
    end
end
display(BC_nodes)


62-element Vector{Any}:
   9
  10
  11
  12
  59
  60
  61
  62
  63
  64
   ⋮
 108
 109
 110
 111
 112
 113
 114
 115
 116